# Use a imagem oficial do Seq da Datalust como base
FROM datalust/seq:latest

# Aceite automaticamente os termos do contrato de licença do Seq
ENV ACCEPT_EULA=Y

# Exponha a porta 80 para permitir conexões com o Seq
EXPOSE 5341
EXPOSE 80

ENV SEQ_ADMIN_USERNAME=admin
ENV SEQ_ADMIN_PASSWORD=admin
