services:
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - desafiobackend-network
        
        
  desafiobackend.web:
    image: desafiobackend.web
    build:
      context: .
      dockerfile: DesafioBackEnd.Api/Dockerfile
#      target: migrations
    ports:
      - "80:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=postgres;Username=postgres;Password=test"
    depends_on:
      - postgres
    networks:
      - desafiobackend-network
      
networks:
  desafiobackend-network:
    driver: bridge  